# -*- coding: utf-8 -*-
"""01_hello_world.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XO4Y23BYRNe6jtmYNL6IB-kXVWKnM-gz

Meu primeiro programa
"""

from google.colab import drive
drive.mount('/content/drive')

print("Hello world")